SELECT
  VIOLATION_CODE,
  COUNT(SUMMONS_NUMBER) AS TICKET_COUNT,
  SUM(FEE_USD)          AS TOTAL_REVENUE_USD
FROM
  {{ref('silver_violation_tickets')}}
GROUP BY
  VIOLATION_CODE
ORDER BY
  TOTAL_REVENUE_USD DESC