SELECT
  REGISTRATION_STATE,
  COUNT(SUMMONS_NUMBER) AS TICKET_COUNT,
FROM
  {{ref('silver_violation_vehicles')}}
WHERE
  REGISTRATION_STATE != 'NY'
GROUP BY
  REGISTRATION_STATE
ORDER BY
  TICKET_COUNT DESC