SELECT
  VIOLATIONS.SUMMONS_NUMBER,
  VIOLATIONS.ISSUE_DATE,
  VIOLATIONS.VIOLATION_CODE,
  VIOLATIONS.IS_MANHATTAN_96TH_ST_BELOW,
  VIOLATIONS.ISSUING_AGENCY,
  VIOLATIONS.VIOLATION_LOCATION,
  VIOLATIONS.VIOLATION_PRECINCT,
  VIOLATIONS.ISSUER_PRECINCT,
  VIOLATIONS.ISSUER_CODE,
  VIOLATIONS.ISSUER_COMMAND,
  VIOLATIONS.ISSUER_SQUAD,
  VIOLATIONS.VIOLATION_TIME,
  VIOLATIONS.VIOLATION_COUNTY,
  VIOLATIONS.VIOLATION_LEGAL_CODE,
  CODES.FEE_USD
FROM
  {{ref('silver_parking_violation')}} AS VIOLATIONS
  LEFT JOIN {{ref('silver_parking_violation_codes')}} AS CODES
  ON VIOLATIONS.VIOLATION_CODE = CODES.VIOLATION_CODE
  AND VIOLATIONS.IS_MANHATTAN_96TH_ST_BELOW = CODES.IS_MANHATTAN_96TH_ST_BELOW