WITH MANHATTAN_VIOLATION_CODES AS (
  SELECT
    VIOLATION_CODE,
    DEFINITION,
    TRUE AS IS_MANHATTAN_96TH_ST_BELOW,
    MANHATTAN_96TH_ST_BELOW AS FEE_USD,
  FROM
    {{ref('bronze_parking_violation_codes')}}
), ALL_OTHER_VIOLATION_CODES AS (
  SELECT
    VIOLATION_CODE,
    DEFINITION,
    FALSE AS IS_MANHATTAN_96TH_ST_BELOW,
    ALL_OTHER_AREAS AS FEE_USD,
  FROM
    {{ref('bronze_parking_violation_codes')}}
)
SELECT
  *
FROM
  MANHATTAN_VIOLATION_CODES
UNION
ALL
SELECT
  *
FROM
  ALL_OTHER_VIOLATION_CODES
ORDER BY
  VIOLATION_CODE ASC