SELECT
  SUMMONS_NUMBER,
  REGISTRATION_STATE,
  PLATE_TYPE,
  VEHICLE_BODY_TYPE,
  VEHICLE_MAKE,
  VEHICLE_EXPIRATION_DATE,
  VEHICLE_COLOR,
  VEHICLE_YEAR
FROM
  {{ ref('silver_parking_violation') }}